<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: class_sig.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ClassRelationProto\RelationCounter instead.
     * @deprecated
     */
    class ClassRelationProto_RelationCounter {}
}
class_exists(ClassRelationProto\RelationCounter::class);
@trigger_error('Proto\ClassRelationProto_RelationCounter is deprecated and will be removed in the next major release. Use Proto\ClassRelationProto\RelationCounter instead', E_USER_DEPRECATED);

