<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ast.proto

namespace Proto;

/**
 * Protobuf type <code>proto.DangerType</code>
 */
class DangerType
{
    /**
     * Generated from protobuf enum <code>DANGER_UNCLASSIFIED_DANGER = 0;</code>
     */
    const DANGER_UNCLASSIFIED_DANGER = 0;
}

