<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ast.proto

namespace Proto;

/**
 * Protobuf type <code>proto.Functionality</code>
 */
class Functionality
{
    /**
     * Generated from protobuf enum <code>UNCLASSIFIED = 0;</code>
     */
    const UNCLASSIFIED = 0;
    /**
     * Generated from protobuf enum <code>SOURCE = 1;</code>
     */
    const SOURCE = 1;
    /**
     * Generated from protobuf enum <code>SINK = 2;</code>
     */
    const SINK = 2;
    /**
     * Generated from protobuf enum <code>DANGER = 3;</code>
     */
    const DANGER = 3;
    /**
     * Generated from protobuf enum <code>PROPAGATE = 4;</code>
     */
    const PROPAGATE = 4;
}

