<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: module.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ModuleTaintWrapper\TaintRule instead.
     * @deprecated
     */
    class ModuleTaintWrapper_TaintRule {}
}
class_exists(ModuleTaintWrapper\TaintRule::class);
@trigger_error('Proto\ModuleTaintWrapper_TaintRule is deprecated and will be removed in the next major release. Use Proto\ModuleTaintWrapper\TaintRule instead', E_USER_DEPRECATED);

