<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: behavior.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ProcessActivity</code>
 */
class ProcessActivity extends \Google\Protobuf\Internal\Message
{
    /**
     * Start new processes
     *
     * Generated from protobuf field <code>string pid = 1;</code>
     */
    private $pid = '';
    /**
     * Generated from protobuf field <code>string cmdline = 2;</code>
     */
    private $cmdline = '';
    /**
     * Generated from protobuf field <code>string exe = 3;</code>
     */
    private $exe = '';
    /**
     * Generated from protobuf field <code>string cwd = 4;</code>
     */
    private $cwd = '';
    /**
     * Generated from protobuf field <code>string root = 5;</code>
     */
    private $root = '';
    /**
     * Generated from protobuf field <code>string ppid = 6;</code>
     */
    private $ppid = '';
    /**
     * Generated from protobuf field <code>string user = 7;</code>
     */
    private $user = '';
    /**
     * Generated from protobuf field <code>string permission = 8;</code>
     */
    private $permission = '';
    /**
     * Generated from protobuf field <code>bool main_process = 9;</code>
     */
    private $main_process = false;
    /**
     * Generated from protobuf field <code>repeated .proto.NetworkActivity network_activities = 10;</code>
     */
    private $network_activities;
    /**
     * Generated from protobuf field <code>repeated .proto.FileActivity file_activities = 11;</code>
     */
    private $file_activities;
    /**
     * Generated from protobuf field <code>repeated .proto.ProcessActivity child_process_activities = 12;</code>
     */
    private $child_process_activities;
    /**
     * Generated from protobuf field <code>repeated .proto.SensitivenActivity sensitive_activities = 13;</code>
     */
    private $sensitive_activities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pid
     *           Start new processes
     *     @type string $cmdline
     *     @type string $exe
     *     @type string $cwd
     *     @type string $root
     *     @type string $ppid
     *     @type string $user
     *     @type string $permission
     *     @type bool $main_process
     *     @type \Proto\NetworkActivity[]|\Google\Protobuf\Internal\RepeatedField $network_activities
     *     @type \Proto\FileActivity[]|\Google\Protobuf\Internal\RepeatedField $file_activities
     *     @type \Proto\ProcessActivity[]|\Google\Protobuf\Internal\RepeatedField $child_process_activities
     *     @type \Proto\SensitivenActivity[]|\Google\Protobuf\Internal\RepeatedField $sensitive_activities
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Behavior::initOnce();
        parent::__construct($data);
    }

    /**
     * Start new processes
     *
     * Generated from protobuf field <code>string pid = 1;</code>
     * @return string
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * Start new processes
     *
     * Generated from protobuf field <code>string pid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkString($var, True);
        $this->pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cmdline = 2;</code>
     * @return string
     */
    public function getCmdline()
    {
        return $this->cmdline;
    }

    /**
     * Generated from protobuf field <code>string cmdline = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCmdline($var)
    {
        GPBUtil::checkString($var, True);
        $this->cmdline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string exe = 3;</code>
     * @return string
     */
    public function getExe()
    {
        return $this->exe;
    }

    /**
     * Generated from protobuf field <code>string exe = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setExe($var)
    {
        GPBUtil::checkString($var, True);
        $this->exe = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cwd = 4;</code>
     * @return string
     */
    public function getCwd()
    {
        return $this->cwd;
    }

    /**
     * Generated from protobuf field <code>string cwd = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCwd($var)
    {
        GPBUtil::checkString($var, True);
        $this->cwd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string root = 5;</code>
     * @return string
     */
    public function getRoot()
    {
        return $this->root;
    }

    /**
     * Generated from protobuf field <code>string root = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRoot($var)
    {
        GPBUtil::checkString($var, True);
        $this->root = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ppid = 6;</code>
     * @return string
     */
    public function getPpid()
    {
        return $this->ppid;
    }

    /**
     * Generated from protobuf field <code>string ppid = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPpid($var)
    {
        GPBUtil::checkString($var, True);
        $this->ppid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user = 7;</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string permission = 8;</code>
     * @return string
     */
    public function getPermission()
    {
        return $this->permission;
    }

    /**
     * Generated from protobuf field <code>string permission = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPermission($var)
    {
        GPBUtil::checkString($var, True);
        $this->permission = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool main_process = 9;</code>
     * @return bool
     */
    public function getMainProcess()
    {
        return $this->main_process;
    }

    /**
     * Generated from protobuf field <code>bool main_process = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setMainProcess($var)
    {
        GPBUtil::checkBool($var);
        $this->main_process = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.NetworkActivity network_activities = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNetworkActivities()
    {
        return $this->network_activities;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.NetworkActivity network_activities = 10;</code>
     * @param \Proto\NetworkActivity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNetworkActivities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\NetworkActivity::class);
        $this->network_activities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.FileActivity file_activities = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFileActivities()
    {
        return $this->file_activities;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.FileActivity file_activities = 11;</code>
     * @param \Proto\FileActivity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFileActivities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\FileActivity::class);
        $this->file_activities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.ProcessActivity child_process_activities = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChildProcessActivities()
    {
        return $this->child_process_activities;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.ProcessActivity child_process_activities = 12;</code>
     * @param \Proto\ProcessActivity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChildProcessActivities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\ProcessActivity::class);
        $this->child_process_activities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.SensitivenActivity sensitive_activities = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSensitiveActivities()
    {
        return $this->sensitive_activities;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.SensitivenActivity sensitive_activities = 13;</code>
     * @param \Proto\SensitivenActivity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSensitiveActivities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\SensitivenActivity::class);
        $this->sensitive_activities = $arr;

        return $this;
    }

}

