
!readFilefs.readFile"fs`h
)readFileSyncfs.readFileSync"fs`h
/getPrivateKeyecdh.getPrivateKey"ecdh`h
AgetPrivateKeydiffieHellman.getPrivateKey"diffieHellman`h
readfs.read"fs`h
readdir
fs.readdir"fs`h
'readdirSyncfs.readdirSync"fs`h
!readSyncfs.readSync"fs`h
)readfilehandle.read"
filehandle`	h
1readFilefilehandle.readFile"
filehandle`
h
/readdirfsPromises.readdir"
fsPromises`h
1readFilefsPromises.readFile"
fsPromises`h
1createReadStreamfs.createReadStream"fs`h
3getTicketKeysserver.getTicketKeys"server`h
%requesthttps.request"https`h
get	https.get"https`h
#requesthttp.request"http`h
)evaluatemodule.evaluate"module`h
evaleval`h
9instantiateWebAssembly.instantiate"WebAssembly`h
KinstantiateStreaming WebAssembly.instantiateStreaming"WebAssembly`h
1compileWebAssembly.compile"WebAssembly`h
CcompileStreamingWebAssembly.compileStreaming"WebAssembly`h
#forkcluster.fork"cluster`h
1runInContextscript.runInContext"script`h
7runInNewContextscript.runInNewContext"script`h
9runInThisContextscript.runInThisContext"script`h
)runInContextvm.runInContext"vm`h
/runInNewContextvm.runInNewContext"vm`h
1runInThisContextvm.runInThisContext"vm`h
!copyFilefs.copyFile"fs`h
)copyFileSyncfs.copyFileSync"fs` h
/execchild_process.exec"child_process`!h
7execFilechild_process.execFile"child_process`"h
/forkchild_process.fork"child_process`#h
1spawnchild_process.spawn"child_process`$h
?execFileSyncchild_process.execFileSync"child_process`%h
7execSyncchild_process.execSync"child_process`&h
9	spawnSyncchild_process.spawnSync"child_process`'h
!sendworker.send"worker`(h
)sendsubprocess.send"
subprocess`)h
!sendsocket.send"socket`*h
%writerequest.write"request`+h
'writeresponse.write"response`,h
ReflectReflect`-h
ProxyProxy`.h
7
pushStreamhttp2stream.pushStream"http2stream`/h
'writeresponse.write"response`0h
'dlopenprocess.dlopen"process`1h
'openinspector.open"	inspector`2h
#postsession.post"session`3h
#writesocket.write"socket`4h
gethttp.get"http`5h…((1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 53) & (31 | 32 | 40 | 41 | 42 | 43 | 44 | 47 | 48 | 49 | 50 | 51 | 52)) | (18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 45 | 46)