
ftp_fgetftp_fget`h
ftp_getftp_get`h
 ftp_nb_fgetftp_nb_fget`h

ftp_nb_get
ftp_nb_get`h
 socket_readsocket_read`h
 socket_recvsocket_recv`h
(socket_recvfromsocket_recvfrom`h
&socket_recvmsgsocket_recvmsg`h
,ssh2_fetch_streamssh2_fetch_stream`	h
$ssh2_scp_recvssh2_scp_recv`
h
6stream_socket_recvfromstream_socket_recvfrom`h
0stream_get_contentsstream_get_contents`h
(stream_get_linestream_get_line`h
*apc_bin_loadfileapc_bin_loadfile`h
freadfread`h
bzreadbzread`h
:
getContentPharFileInfo::getContent"PharFileInfo`h
0addFromStringPhar::addFromString"Phar`h
8addFromStringPharData::addFromString"PharData`h
&zip_entry_readzip_entry_read`h
zip_readzip_read`h
0addFileZipArchive::addFile"
ZipArchive`h
<addFromStringZipArchive::addFromString"
ZipArchive`h
gzreadgzread`h
dio_readdio_read`h
readdirreaddir`h
filefile`h
,file_get_contentsfile_get_contents`h
fgetcfgetc`h
fgetcsvfgetcsv`h
fgetsfgets`h
fgetssfgetss` h
freadfread`!h
fscanffscanf`"h
.move_uploaded_filemove_uploaded_file`#h
eio_readeio_read`$h
 eio_readdireio_readdir`%h
$eio_readaheadeio_readahead`&h
,swoole_async_readswoole_async_read`'h
4swoole_async_readfileswoole_async_readfile`(h
.swoole_load_moduleswoole_load_module`)h
&exif_read_dataexif_read_data`*h
&read_exif_dataread_exif_data`+h
gzfilegzfile`,h
gzgetcgzgetc`-h
gzgetsgzgets`.h
gzgetssgzgetss`/h
readfilereadfile`0h

readgzfile
readgzfile`1h
readlinkreadlink`2h
&highlight_filehighlight_file`3h
 show_sourceshow_source`4h
4radius_send_requestradius_send_requestB``5h
ftp_fputftp_fputB``6h
ftp_putftp_putB``7h
$ftp_nb_fputftp_nb_fputB``8h
"
ftp_nb_put
ftp_nb_putB``9h
$socket_sendsocket_sendB``:h
*socket_sendmsgsocket_sendmsgB``;h
,socket_sendtosocket_sendtoB`B``<h
&socket_writesocket_writeB``=h
(ssh2_scp_sendssh2_scp_sendB``>h
:stream_socket_sendtostream_socket_sendtoB`B``?h
2apc_bin_dumpfileapc_bin_dumpfileB`B``@h
fwritefwriteB``Ah
bzwritebzwriteB``Bh
gzwritegzwriteB``Ch
gzputsgzputsB``Dh
 	dio_write	dio_writeB``Eh
0file_put_contentsfile_put_contentsB``Fh
fputcsvfputcsvB``Gh
fputsfputsB``Hh
fwritefwriteB``Ih
 	eio_write	eio_writeB``Jh
2swoole_async_writeswoole_async_writeB``Kh
:swoole_async_writefileswoole_async_writefileB``Lh
 fprintffprintfB`B``Mh
"vfprintfvfprintfB`B``Nh
.yaml_emit_fileyaml_emit_fileB`B``Oh
"
yaml_parse
yaml_parseB``Ph
,yaml_parse_fileyaml_parse_fileB``Qh
6mb_send_mailmb_send_mailB`B`B`B`B``Rh
&mailmailB`B`B`B`B``Sh
 	fpassthru	fpassthruB``Th
"
gzpassthru
gzpassthruB``Uh
fopenfopenB``Vh
zip_openzip_openB``Wh
fdf_openfdf_openB``Xh
&setproctitlesetproctitleB``Yh
*setthreadtitlesetthreadtitleB``Zh
*expect_expectlexpect_expectlB``[h
&expect_popenexpect_popenB``\h
"
pcntl_exec
pcntl_execB``]h

pcntl_fork
pcntl_fork`^h
"pcntl_signalpcntl_signal`_h
&posix_getloginposix_getlogin``h
execexecB``ah
popenpopenB``bh
passthrupassthruB``ch
 	proc_open	proc_openB``dh
"
shell_exec
shell_execB``eh
systemsystemB``fh
$runThreaded::run"Threaded`gh
$startThread::start"Thread`hh
"submitPool::submit"Pool`ih
,startpht\Thread::start"
pht\Thread`jh
,runpht\Runnable::run"pht\Runnable`kh
 	ftp_rmdir	ftp_rmdirB``lh
"
ftp_delete
ftp_deleteB``mh
ftp_rawftp_rawB``nh
ftp_execftp_execB``oh
 	curl_exec	curl_execB``ph
,curl_multi_execcurl_multi_execB``qh
*ssh2_connectssh2_connectB`B``rh

ssh2_shell
ssh2_shell`sh
(ssh2_tunnelssh2_tunnelB`B``th
 	ssh2_exec	ssh2_execB``uh
.ssh2_sftp_unlinkssh2_sftp_unlinkB``vh
,apc_delete_fileapc_delete_fileB``wh
linklinkB``xh
deletedeleteB``yh
unlinkunlinkB``zh
rmdirrmdirB``{h
"
eio_unlink
eio_unlinkB``|h
 	eio_rmdir	eio_rmdirB``}h
.apc_compile_fileapc_compile_fileB``~h
4override_functionoverride_functionB`B``h
3bcompiler_load_exebcompiler_load_exeB``Äh
+bcompiler_loadbcompiler_loadB``Åh
5bcompiler_parse_classbcompiler_parse_class`Çh
+bcompiler_readbcompiler_readB``Éh

Reflection
Reflection`Ñh
)ReflectionClassReflectionClass`Öh
9ReflectionZendExtensionReflectionZendExtension`Üh
1ReflectionExtensionReflectionExtension`áh
/ReflectionFunctionReflectionFunction`àh
+ReflectionMethodReflectionMethod`âh
7opcache_compile_fileopcache_compile_fileB``äh
1uopz_add_functionuopz_add_functionB``ãh
-classkit_importclasskit_importB``åh
5classkit_method_addclasskit_method_addB``çh
?classkit_method_redefineclasskit_method_redefineB``éh
evalevalB``èh
9parsekit_compile_fileparsekit_compile_fileB``êh
=parsekit_compile_stringparsekit_compile_stringB``ëh
call	Lua::call"Lua`íh
!eval	Lua::eval"LuaB``ìh
'includeLua::include"LuaB``îh
assertassertB``ïh
#preg_replacepreg_replace`ñh
!preg_filterpreg_filter`óh
5preg_replace_callbackpreg_replace_callback`òh
+mb_eregi_replacemb_eregi_replace`ôh
)mb_ereg_replacemb_ereg_replace`öh
-create_functioncreate_functionB``õh
includeincludeB``úh
/php_check_syntaxphp_check_syntaxB``ùh
)runkit_importrunkit_importB``ûh
5runkit_function_addrunkit_function_addB``üh
5runkit_constant_addrunkit_constant_addB``†h
1runkit_method_addrunkit_method_addB``°h
?runkit_function_redefinerunkit_function_redefineB``¢h
?runkit_constant_redefinerunkit_constant_redefineB``£h
;runkit_method_redefinerunkit_method_redefineB``§h
virtualvirtualB``•h
dldlB``¶h˝((1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52) & (53 | 54 | 55 | 56 | 57 | 58 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 76 | 77 | 78 | 79 | 80 | 81 | 82 | 83 | 84 | 85 | 86 | 87 | 88)) | (89 | 90 | 91 | 92 | 93 | 94 | 95 | 96 | 97 | 98 | 99 | 100 | 101 | 102 | 103 | 104 | 105 | 106 | 107 | 108 | 109 | 110 | 111 | 112 | 113 | 114 | 115 | 116 | 117 | 118 | 119 | 120 | 121 | 122 | 123 | 124 | 125 | 126 | 127 | 128 | 129 | 130 | 131 | 132 | 133 | 134 | 135 | 136 | 137 | 138 | 139 | 140 | 141 | 142 | 143 | 144 | 145 | 146 | 147 | 148 | 149 | 150 | 151 | 152 | 153 | 154 | 155 | 156 | 157 | 158 | 159 | 160 | 161 | 162 | 163 | 164 | 165 | 166)