<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: behavior.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.AnalysisResult</code>
 */
class AnalysisResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.PackageInfo package_info = 1;</code>
     */
    private $package_info = null;
    /**
     * Generated from protobuf field <code>repeated .proto.DynamicAnalysis dynamic_results = 2;</code>
     */
    private $dynamic_results;
    /**
     * Generated from protobuf field <code>repeated .proto.StaticAnalysis static_results = 3;</code>
     */
    private $static_results;
    /**
     * Generated from protobuf field <code>repeated .proto.ConcolicAnalysis concolic_results = 4;</code>
     */
    private $concolic_results;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\PackageInfo $package_info
     *     @type \Proto\DynamicAnalysis[]|\Google\Protobuf\Internal\RepeatedField $dynamic_results
     *     @type \Proto\StaticAnalysis[]|\Google\Protobuf\Internal\RepeatedField $static_results
     *     @type \Proto\ConcolicAnalysis[]|\Google\Protobuf\Internal\RepeatedField $concolic_results
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Behavior::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.PackageInfo package_info = 1;</code>
     * @return \Proto\PackageInfo
     */
    public function getPackageInfo()
    {
        return $this->package_info;
    }

    /**
     * Generated from protobuf field <code>.proto.PackageInfo package_info = 1;</code>
     * @param \Proto\PackageInfo $var
     * @return $this
     */
    public function setPackageInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\PackageInfo::class);
        $this->package_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.DynamicAnalysis dynamic_results = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDynamicResults()
    {
        return $this->dynamic_results;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.DynamicAnalysis dynamic_results = 2;</code>
     * @param \Proto\DynamicAnalysis[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDynamicResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\DynamicAnalysis::class);
        $this->dynamic_results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.StaticAnalysis static_results = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStaticResults()
    {
        return $this->static_results;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.StaticAnalysis static_results = 3;</code>
     * @param \Proto\StaticAnalysis[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStaticResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\StaticAnalysis::class);
        $this->static_results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.ConcolicAnalysis concolic_results = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConcolicResults()
    {
        return $this->concolic_results;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.ConcolicAnalysis concolic_results = 4;</code>
     * @param \Proto\ConcolicAnalysis[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConcolicResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\ConcolicAnalysis::class);
        $this->concolic_results = $arr;

        return $this;
    }

}

