<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: class_sig.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ClassAttributeProto</code>
 */
class ClassAttributeProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string class_name = 1;</code>
     */
    private $class_name = '';
    /**
     * Generated from protobuf field <code>string super_class_name = 2;</code>
     */
    private $super_class_name = '';
    /**
     * Generated from protobuf field <code>repeated string interface_class_names = 3;</code>
     */
    private $interface_class_names;
    /**
     * Generated from protobuf field <code>string package_name = 4;</code>
     */
    private $package_name = '';
    /**
     * Generated from protobuf field <code>bool is_entry_point = 5;</code>
     */
    private $is_entry_point = false;
    /**
     * Generated from protobuf field <code>repeated string static_field_strings = 6;</code>
     */
    private $static_field_strings;
    /**
     * Generated from protobuf field <code>repeated string instance_field_strings = 7;</code>
     */
    private $instance_field_strings;
    /**
     * Generated from protobuf field <code>repeated string permission_strings = 8;</code>
     */
    private $permission_strings;
    /**
     * Generated from protobuf field <code>repeated .proto.MethodAttributeProto methods = 9;</code>
     */
    private $methods;
    /**
     * Generated from protobuf field <code>string outer_class_name = 10;</code>
     */
    private $outer_class_name = '';
    /**
     * Generated from protobuf field <code>string modifiers = 11;</code>
     */
    private $modifiers = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $class_name
     *     @type string $super_class_name
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $interface_class_names
     *     @type string $package_name
     *     @type bool $is_entry_point
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $static_field_strings
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $instance_field_strings
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $permission_strings
     *     @type \Proto\MethodAttributeProto[]|\Google\Protobuf\Internal\RepeatedField $methods
     *     @type string $outer_class_name
     *     @type string $modifiers
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ClassSig::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string class_name = 1;</code>
     * @return string
     */
    public function getClassName()
    {
        return $this->class_name;
    }

    /**
     * Generated from protobuf field <code>string class_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClassName($var)
    {
        GPBUtil::checkString($var, True);
        $this->class_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string super_class_name = 2;</code>
     * @return string
     */
    public function getSuperClassName()
    {
        return $this->super_class_name;
    }

    /**
     * Generated from protobuf field <code>string super_class_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSuperClassName($var)
    {
        GPBUtil::checkString($var, True);
        $this->super_class_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string interface_class_names = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInterfaceClassNames()
    {
        return $this->interface_class_names;
    }

    /**
     * Generated from protobuf field <code>repeated string interface_class_names = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInterfaceClassNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->interface_class_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string package_name = 4;</code>
     * @return string
     */
    public function getPackageName()
    {
        return $this->package_name;
    }

    /**
     * Generated from protobuf field <code>string package_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPackageName($var)
    {
        GPBUtil::checkString($var, True);
        $this->package_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_entry_point = 5;</code>
     * @return bool
     */
    public function getIsEntryPoint()
    {
        return $this->is_entry_point;
    }

    /**
     * Generated from protobuf field <code>bool is_entry_point = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEntryPoint($var)
    {
        GPBUtil::checkBool($var);
        $this->is_entry_point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string static_field_strings = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStaticFieldStrings()
    {
        return $this->static_field_strings;
    }

    /**
     * Generated from protobuf field <code>repeated string static_field_strings = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStaticFieldStrings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->static_field_strings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string instance_field_strings = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInstanceFieldStrings()
    {
        return $this->instance_field_strings;
    }

    /**
     * Generated from protobuf field <code>repeated string instance_field_strings = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInstanceFieldStrings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->instance_field_strings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string permission_strings = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPermissionStrings()
    {
        return $this->permission_strings;
    }

    /**
     * Generated from protobuf field <code>repeated string permission_strings = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPermissionStrings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->permission_strings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.MethodAttributeProto methods = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMethods()
    {
        return $this->methods;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.MethodAttributeProto methods = 9;</code>
     * @param \Proto\MethodAttributeProto[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMethods($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\MethodAttributeProto::class);
        $this->methods = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string outer_class_name = 10;</code>
     * @return string
     */
    public function getOuterClassName()
    {
        return $this->outer_class_name;
    }

    /**
     * Generated from protobuf field <code>string outer_class_name = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setOuterClassName($var)
    {
        GPBUtil::checkString($var, True);
        $this->outer_class_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string modifiers = 11;</code>
     * @return string
     */
    public function getModifiers()
    {
        return $this->modifiers;
    }

    /**
     * Generated from protobuf field <code>string modifiers = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setModifiers($var)
    {
        GPBUtil::checkString($var, True);
        $this->modifiers = $var;

        return $this;
    }

}

