<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: class_sig.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ClassRelationProto\RelationType instead.
     * @deprecated
     */
    class ClassRelationProto_RelationType {}
}
class_exists(ClassRelationProto\RelationType::class);
@trigger_error('Proto\ClassRelationProto_RelationType is deprecated and will be removed in the next major release. Use Proto\ClassRelationProto\RelationType instead', E_USER_DEPRECATED);

