<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: behavior.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.DynamicAnalysis</code>
 */
class DynamicAnalysis extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.AnalysisType analysis_type = 1;</code>
     */
    private $analysis_type = 0;
    /**
     * Generated from protobuf field <code>.proto.ExecutionType exe_type = 2;</code>
     */
    private $exe_type = 0;
    /**
     * User running the program, e.g. root, maloss etc.
     *
     * Generated from protobuf field <code>string exe_user = 3;</code>
     */
    private $exe_user = '';
    /**
     * Generated from protobuf field <code>string timestamp = 4;</code>
     */
    private $timestamp = '';
    /**
     * Generated from protobuf field <code>string end_timestamp = 5;</code>
     */
    private $end_timestamp = '';
    /**
     * Generated from protobuf field <code>.proto.ProcessActivity process_activity = 6;</code>
     */
    private $process_activity = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $analysis_type
     *     @type int $exe_type
     *     @type string $exe_user
     *           User running the program, e.g. root, maloss etc.
     *     @type string $timestamp
     *     @type string $end_timestamp
     *     @type \Proto\ProcessActivity $process_activity
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Behavior::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.AnalysisType analysis_type = 1;</code>
     * @return int
     */
    public function getAnalysisType()
    {
        return $this->analysis_type;
    }

    /**
     * Generated from protobuf field <code>.proto.AnalysisType analysis_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAnalysisType($var)
    {
        GPBUtil::checkEnum($var, \Proto\AnalysisType::class);
        $this->analysis_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.ExecutionType exe_type = 2;</code>
     * @return int
     */
    public function getExeType()
    {
        return $this->exe_type;
    }

    /**
     * Generated from protobuf field <code>.proto.ExecutionType exe_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setExeType($var)
    {
        GPBUtil::checkEnum($var, \Proto\ExecutionType::class);
        $this->exe_type = $var;

        return $this;
    }

    /**
     * User running the program, e.g. root, maloss etc.
     *
     * Generated from protobuf field <code>string exe_user = 3;</code>
     * @return string
     */
    public function getExeUser()
    {
        return $this->exe_user;
    }

    /**
     * User running the program, e.g. root, maloss etc.
     *
     * Generated from protobuf field <code>string exe_user = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setExeUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->exe_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 4;</code>
     * @return string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string end_timestamp = 5;</code>
     * @return string
     */
    public function getEndTimestamp()
    {
        return $this->end_timestamp;
    }

    /**
     * Generated from protobuf field <code>string end_timestamp = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.ProcessActivity process_activity = 6;</code>
     * @return \Proto\ProcessActivity
     */
    public function getProcessActivity()
    {
        return $this->process_activity;
    }

    /**
     * Generated from protobuf field <code>.proto.ProcessActivity process_activity = 6;</code>
     * @param \Proto\ProcessActivity $var
     * @return $this
     */
    public function setProcessActivity($var)
    {
        GPBUtil::checkMessage($var, \Proto\ProcessActivity::class);
        $this->process_activity = $var;

        return $this;
    }

}

