<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: module.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ModuleFlow\FlowInfo instead.
     * @deprecated
     */
    class ModuleFlow_FlowInfo {}
}
class_exists(ModuleFlow\FlowInfo::class);
@trigger_error('Proto\ModuleFlow_FlowInfo is deprecated and will be removed in the next major release. Use Proto\ModuleFlow\FlowInfo instead', E_USER_DEPRECATED);

