<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: class_sig.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.PkgClassMethodResults</code>
 */
class PkgClassMethodResults extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.PkgClassMethodResult pkgs = 1;</code>
     */
    private $pkgs;
    /**
     * Generated from protobuf field <code>uint64 timestamp = 2;</code>
     */
    private $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\PkgClassMethodResult[]|\Google\Protobuf\Internal\RepeatedField $pkgs
     *     @type int|string $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ClassSig::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.PkgClassMethodResult pkgs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPkgs()
    {
        return $this->pkgs;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.PkgClassMethodResult pkgs = 1;</code>
     * @param \Proto\PkgClassMethodResult[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPkgs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\PkgClassMethodResult::class);
        $this->pkgs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 2;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

}

