<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ast.proto

namespace Proto;

/**
 * Protobuf type <code>proto.PropagateType</code>
 */
class PropagateType
{
    /**
     * Generated from protobuf enum <code>PROPAGATE_UNCLASSIFIED = 0;</code>
     */
    const PROPAGATE_UNCLASSIFIED = 0;
    /**
     * Generated from protobuf enum <code>PROPAGATE_ASSIGN = 1;</code>
     */
    const PROPAGATE_ASSIGN = 1;
    /**
     * Calls can affect the results by return value or reference argument
     *
     * Generated from protobuf enum <code>PROPAGATE_CALL = 2;</code>
     */
    const PROPAGATE_CALL = 2;
    /**
     * Generated from protobuf enum <code>PROPAGATE_SYSCALL = 3;</code>
     */
    const PROPAGATE_SYSCALL = 3;
    /**
     * Generated from protobuf enum <code>PROPAGATE_LIBCALL = 4;</code>
     */
    const PROPAGATE_LIBCALL = 4;
}

