<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: behavior.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SensitivenActivity</code>
 */
class SensitivenActivity extends \Google\Protobuf\Internal\Message
{
    /**
     * FIXME: Read/Write sensitive information  or performing privileged operations via specific system calls
     *
     * Generated from protobuf field <code>string pid = 1;</code>
     */
    private $pid = '';
    /**
     * Generated from protobuf field <code>string cmdline = 2;</code>
     */
    private $cmdline = '';
    /**
     * Generated from protobuf field <code>string exe = 3;</code>
     */
    private $exe = '';
    /**
     * Generated from protobuf field <code>string cwd = 4;</code>
     */
    private $cwd = '';
    /**
     * Generated from protobuf field <code>string root = 5;</code>
     */
    private $root = '';
    /**
     * Generated from protobuf field <code>string ppid = 6;</code>
     */
    private $ppid = '';
    /**
     * Generated from protobuf field <code>string user = 7;</code>
     */
    private $user = '';
    /**
     * Generated from protobuf field <code>string syscall = 8;</code>
     */
    private $syscall = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $pid
     *           FIXME: Read/Write sensitive information  or performing privileged operations via specific system calls
     *     @type string $cmdline
     *     @type string $exe
     *     @type string $cwd
     *     @type string $root
     *     @type string $ppid
     *     @type string $user
     *     @type string $syscall
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Behavior::initOnce();
        parent::__construct($data);
    }

    /**
     * FIXME: Read/Write sensitive information  or performing privileged operations via specific system calls
     *
     * Generated from protobuf field <code>string pid = 1;</code>
     * @return string
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * FIXME: Read/Write sensitive information  or performing privileged operations via specific system calls
     *
     * Generated from protobuf field <code>string pid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkString($var, True);
        $this->pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cmdline = 2;</code>
     * @return string
     */
    public function getCmdline()
    {
        return $this->cmdline;
    }

    /**
     * Generated from protobuf field <code>string cmdline = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCmdline($var)
    {
        GPBUtil::checkString($var, True);
        $this->cmdline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string exe = 3;</code>
     * @return string
     */
    public function getExe()
    {
        return $this->exe;
    }

    /**
     * Generated from protobuf field <code>string exe = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setExe($var)
    {
        GPBUtil::checkString($var, True);
        $this->exe = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cwd = 4;</code>
     * @return string
     */
    public function getCwd()
    {
        return $this->cwd;
    }

    /**
     * Generated from protobuf field <code>string cwd = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCwd($var)
    {
        GPBUtil::checkString($var, True);
        $this->cwd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string root = 5;</code>
     * @return string
     */
    public function getRoot()
    {
        return $this->root;
    }

    /**
     * Generated from protobuf field <code>string root = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRoot($var)
    {
        GPBUtil::checkString($var, True);
        $this->root = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ppid = 6;</code>
     * @return string
     */
    public function getPpid()
    {
        return $this->ppid;
    }

    /**
     * Generated from protobuf field <code>string ppid = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPpid($var)
    {
        GPBUtil::checkString($var, True);
        $this->ppid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user = 7;</code>
     * @return string
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>string user = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string syscall = 8;</code>
     * @return string
     */
    public function getSyscall()
    {
        return $this->syscall;
    }

    /**
     * Generated from protobuf field <code>string syscall = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSyscall($var)
    {
        GPBUtil::checkString($var, True);
        $this->syscall = $var;

        return $this;
    }

}

